# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Tibber Meter Uploader
version: "1.2.0"
slug: tibber-meter-uploader
description: An add-on to upload meter data to Tibber.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
